# Generated by Django 3.1.2 on 2022-09-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('town', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('card_last_four', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.address')),
            ],
        ),
        migrations.CreateModel(
            name='DonorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('max_goal', models.IntegerField()),
                ('so_far', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proj.donorlist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.project')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=200)),
                ('max_amount', models.IntegerField()),
                ('current_ammount', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.project')),
            ],
        ),
        migrations.CreateModel(
            name='DonorTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField()),
                ('currency', models.CharField(blank=True, max_length=255)),
                ('anonymous', models.CharField(default=False, max_length=20)),
                ('specific_facilities', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='proj.facilitylist')),
            ],
        ),
        migrations.AddField(
            model_name='donorlist',
            name='transactions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proj.donortransactions'),
        ),
    ]
